port CC1101 to SIGNALESP (based on locutus "D1 mini CC1101 shield")
RFD-FHEM/SIGNALESP pull request #2
Opened 2017-07-15 17:29 UTC by habeIchVergessen

2017-08-17 19:38 UTC, sidey79 requested changes
Schau dir mal meine Kommentare an

2017-08-17 19:38 UTC, sidey79 commented on SIGNALESP/cc1101.h
> +	#ifndef ESP8266
Was könnte denn hier noch verwendet werdenm anstelle eines ESP8266?

2017-08-17 19:38 UTC, sidey79 commented on SIGNALESP/cc1101.h
> +	#include <SPI.h>
Den Teil haben wir beim SIGNALDuino nicht

2017-08-17 19:38 UTC, sidey79 commented on SIGNALESP/SIGNALESP.ino
> +  if (Serial.available()) {
Was genau soll dieser Teil bewirken?

2017-08-17 19:38 UTC, sidey79 commented on SIGNALESP/cc1101.h
> +//		#define SS					  8
wieso hast Du diese Zeile auskommentiert?

2017-08-17 19:38 UTC, sidey79 commented on SIGNALESP/cc1101.h
> +			#define PIN_SEND              9   // gdo0Pin TX out
in der SIGNAL_ESP.ino sind die PINs wie folgt gesetzt:
``` 
#define PIN_RECEIVE            2
  #define PIN_LED                16		  
  #define PIN_SEND               0		  
```

2017-08-17 19:52 UTC, habeIchVergessen commented on SIGNALESP/cc1101.h
> +//		#define SS					  8
SS ist für ein ESP8266 bereits definiert.

2017-08-17 19:54 UTC, habeIchVergessen commented on SIGNALESP/cc1101.h
> +	#include <SPI.h>
ESP8266 hat eine einfache library.

2017-08-17 19:55 UTC, habeIchVergessen commented on SIGNALESP/cc1101.h
> +	#ifndef ESP8266
ggf. wird cc1101.h eine Art library (mehrere Plattformen).

2017-08-17 20:07 UTC, habeIchVergessen reviewed
kann ich gerne per Compiler-Option ausschaltbar machen.
Hatte anfänglich Probleme mit meinen cc1101-Platinen. Scheint 2 Rev. zu geben, die auf unterschiedlichen Ports antworten. Hatte dazu schon im [Forum](https://forum.fhem.de/index.php/topic,66809.msg661143.html#msg661143) rumgefragt und keine Antwort bekommen.

2017-08-17 20:07 UTC, habeIchVergessen commented on SIGNALESP/SIGNALESP.ino
> +  if (Serial.available()) {
in der Entwicklungsumgebung per serieller Eingabe etwas Debug-Zeug

2017-08-17 21:05 UTC, sidey79 commented on SIGNALESP/cc1101.h
> +//		#define SS					  8
Wieso steht dann im #if noch defined(ARDUINO_AVR_ICT_BOARDS_ICT_BOARDS_AVR_RADINOCC1101) ?

2017-08-17 21:06 UTC, sidey79 commented on SIGNALESP/cc1101.h
> +	#include <SPI.h>
Gibts für den Arduino doch auch. Hat die Implementierung von der quelldatei nicht funktioniert?

2017-08-17 21:11 UTC, habeIchVergessen commented on SIGNALESP/cc1101.h
> +	#include <SPI.h>
Hab es nur kopiert und die nötigsten Änderung eingebaut, damit es durch den Compiler geht.

2017-08-17 21:11 UTC, habeIchVergessen commented on SIGNALESP/cc1101.h
> +//		#define SS					  8
Hab es nur kopiert und die nötigsten Änderung eingebaut, damit es durch den Compiler geht.

2017-08-18 09:50 UTC, susisstrolch reviewed
Warum wird 'u' für die Uptime verwendet?
Beim Original war es - wie beim CUL - ein 't'...

2017-08-18 09:56 UTC, habeIchVergessen commented on SIGNALESP/cc1101.h
> +	#include <SPI.h>
anbei die Compiler-Fehler ohne SPI-library

In file included from SIGNALESP\SIGNALESP.ino:38:0:

sketch\cc1101.h: In function 'uint8_t cc1101::sendSPI(uint8_t)':

cc1101.h:223: error: 'SPDR' was not declared in this scope
   SPDR = val;                                      // transfer byte via SPI
   ^

cc1101.h:224: error: 'SPSR' was not declared in this scope
   while (!(SPSR & _BV(SPIF)));                     // wait until SPI operation is terminated
            ^

cc1101.h:224: error: 'SPIF' was not declared in this scope
   while (!(SPSR & _BV(SPIF)));                     // wait until SPI operation is terminated
                       ^

packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Arduino.h:184:25: note: in definition of macro '_BV'
 #define _BV(b) (1UL << (b))
                         ^

exit status 1
'SPDR' was not declared in this scope

2017-08-18 10:29 UTC, habeIchVergessen commented
der Code (Eingabe über serielle Schnittstelle) ist nur für Entwicklungszwecke gedacht und muss keine, woraus auch immer abgeleiteten, Konventionen erfüllen.

2017-08-18 20:46 UTC, merged